backend:
  name: git-gateway
  branch: main

media_folder: public/images/blog
public_folder: /images/blog

collections:
  - name: blog
    label: Blog Posts
    folder: src/content/blog
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Descripción SEO", name: "description", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: [] }
      - { label: "Imagen destacada", name: "featured_image", widget: "image", required: false }
      - { label: "Contenido", name: "body", widget: "markdown" }
